### ISSUE TITLE
ImportError: cannot import name 'cython_nms'

### ISSUE THREAD

**Issue by 1803643593** [mj000001/Object-Detection-And-Tracking#1]
ImportError: cannot import name 'cython_nms'   Can you help me explain why?

**Comment by mj000001** [comment]
You can follow [longcw's repo](https://github.com/longcw/faster_rcnn_pytorch).
You may should install cython and run
`
cd faster_rcnn_pytorch/faster_rcnn
`
`
./make.sh`
